runtime: python311  # Use your Python version
entrypoint: gunicorn -w 1 -b :$PORT app:app  # Run Flask using Gunicorn

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
